GET http://localhost:5001/user

###

GET http://localhost:5001/hashPassword

###

GET http://localhost:5001/api/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiIxMTAxMTAxMTAxIiwiaWF0IjoxNzY5NDM5OTQ0LCJleHAiOjE3Njk0NDE3NDR9.ZmCaxQiUmnEUYomL42N6ofOmgGwg0m1Jvi9Uns3uQoA

###

POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123456"
}

###

POST http://localhost:5001/api/auth/logout